### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AAppole1** [HenestrosaConH/audiotext#4]
Hi!
I am not very familiar with this stuff and I require some assistance. I am using macos and I have installed ffmpeg and downloaded audiotext unix file and when I try to open it it just opens the text editor? Do I need to run the file with ffmpeg? Could you help me pelase :). I would really like to learn and use this program it seems really useful to me as a student.

**Comment by HenestrosaConH** [comment]
Hi there!

Could you please paste the text here so I can see what's wrong?

**Comment by AAppole1** [comment]
<img width="1393" alt="CleanShot 2023-04-03 at 14 37 35@2x" src="https://user-images.githubusercontent.com/123331517/229498592-b3cb5737-c7b3-425a-bbc7-6b6e12ffaf30.png">

Hi! Here is the screenshot of the text file. It like open the whole code in it or something? Do you know what to do?

**Comment by HenestrosaConH** [comment]
OK, I'm going to take a look at the project to see what's the issue with the Unix distribution. I'll get back as soon as I find something!

**Comment by AAppole1** [comment]
Ok thank you! Let me know if I should try something to solve this issue

**Comment by AAppole1** [comment]
Hi! Now the audiotext file is executable, but I still have issues with it. It asks permission to run all the scripts is there a way to override it, to have permission to all of them. And after giving them permission it still gives me an error :('
<img width="231" alt="CleanShot 2023-04-03 at 21 06 14@2x" src="https://user-images.githubusercontent.com/123331517/229595263-ac40b451-28fc-4d84-a478-cf3ef5673fcd.png">
<img width="948" alt="CleanShot 2023-04-03 at 21 22 57@2x" src="https://user-images.githubusercontent.com/123331517/229595357-957d9d9b-ce0e-40ff-a05c-030a4363465b.png">
<img width="945" alt="CleanShot 2023-04-03 at 21 23 12@2x" src="https://user-images.githubusercontent.com/123331517/229595448-d14d7058-3e51-4259-b02f-a0ff2c09639e.png">
<img width="953" alt="CleanShot 2023-04-03 at 21 23 36@2x" src="https://user-images.githubusercontent.com/123331517/229595482-3bd1b649-5856-42a4-876d-0e7b7632ca0b.png">
<img width="951" alt="CleanShot 2023-04-03 at 21 24 00@2x" src="https://user-images.githubusercontent.com/123331517/229595507-8339a10b-bbb9-48d8-98d6-6228be0fc80c.png">

**Comment by HenestrosaConH** [comment]
I see... It seems that there is something wrong with a dependency of the project. Could you please tell me the model of your Mac?

**Comment by AAppole1** [comment]
Hi! 
I have the 2020 macbook pro m1 running Ventura 13.2.1

**Comment by HenestrosaConH** [comment]
I have the same exact model with the same macOS version and everything is running fine in my computer. I have been looking for more details on this issue and it seems that I would have to create an Apple developer account (which costs 99$ per year) in order to sign the binaries and allow other users to execute the program flawlessly. I will look into this issue further and I will get back as soon as I find something useful to overcome the issue but, at this moment, I wouldn't be interested in creating an Apple developer account. 

These are the sites that have led me in the right direction:
1. https://stackoverflow.com/questions/66983242/security-issues-downloading-application-for-macos-library-load-disallowed-by
2. https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing
3. https://gist.github.com/txoof/0636835d3cc65245c6288b2374799c43

For the time being, I think you could use [freesubtitles.ai](https://freesubtitles.ai/), which is a website that will let you transcribe your audios/videos for free.

**Comment by AAppole1** [comment]
Ok. Thank you for all your help. I will try this program also with my windows pc soon hope it works with it :).
