### ISSUE TITLE
[Feature] Arabic 

### ISSUE THREAD

**Issue by SWxEng** [HenestrosaConH/audiotext#7]
Hi @HenestrosaConH 

Add Arabic Translation in audiotext

**Comment by HenestrosaConH** [comment]
Hello.

As far as I'm concerned, Arabic is already suported (لعربية). Please tell me if you encounter any issue with it. I'm going to update the README and the list of languages displayed on the ComboBox to also show the name of the language in English.

Thank you for the feedback.

Regards.

**Comment by SWxEng** [comment]
ok

**Comment by HenestrosaConH** [comment]
Even though Arabic was available, I've released a [new release version](https://github.com/HenestrosaConH/audiotext/releases/tag/v1.2.4) that changes the names of the languages to their English spellings instead of their spellings in their respective languages. 

Again, feel free to create a new issue if you find any bugs or possible improvements.

Regards.
